//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuphat
    {
        public string MaPhieuPhat { get; set; }
        public string MaThe { get; set; }
        public string TienTra { get; set; }
        public string ThongBao { get; set; }
    
        public virtual tbThe tbThe { get; set; }
    }
}
