//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTVEntities : DbContext
    {
        public QLTVEntities()
            : base("name=QLTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<phieuphat> phieuphats { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbChoDuyet> tbChoDuyets { get; set; }
        public virtual DbSet<tbDauSach> tbDauSaches { get; set; }
        public virtual DbSet<tbDG> tbDGs { get; set; }
        public virtual DbSet<tbMK> tbMKs { get; set; }
        public virtual DbSet<tbNXB> tbNXBs { get; set; }
        public virtual DbSet<tbPhieuMuon> tbPhieuMuons { get; set; }
        public virtual DbSet<tbTG> tbTGs { get; set; }
        public virtual DbSet<tbThe> tbThes { get; set; }
    }
}
