//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDauSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDauSach()
        {
            this.tbChoDuyets = new HashSet<tbChoDuyet>();
        }
    
        public string MaDauSach { get; set; }
        public string TenSach { get; set; }
        public string MaNXB { get; set; }
        public string MaTG { get; set; }
        public string NamXuatBan { get; set; }
        public string ChuyenNganh { get; set; }
        public int SoLuong { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbChoDuyet> tbChoDuyets { get; set; }
        public virtual tbNXB tbNXB { get; set; }
        public virtual tbTG tbTG { get; set; }
    }
}
