//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDG()
        {
            this.tbThes = new HashSet<tbThe>();
        }
    
        public string MaDG { get; set; }
        public string TenDG { get; set; }
        public string ChucVu { get; set; }
        public string Lop { get; set; }
        public string Khoa { get; set; }
        public string NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbThe> tbThes { get; set; }
    }
}
