//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhieuMuon
    {
        public string MaPhieu { get; set; }
        public string MaDauSach { get; set; }
        public string MaThe { get; set; }
        public string NgayMuon { get; set; }
        public string NgayTra { get; set; }
    }
}
